### ISSUE TITLE
Travis update causes test docker container to fail to start

### ISSUE THREAD

**Issue by llorllale** [llorllale/youtrack-api#107]
There was an [update to Travis CI](https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch) that broke our build (see [this](https://github.com/llorllale/youtrack-api/pull/106#issuecomment-352146557) comment). The Travis team is tracking all reports here: travis-ci/travis-ci#8870.

While they fix things, let's use the workaround posted in their blog. In `.travis.yml`:
```yml
sudo: required
dist: trusty
group: deprecated-2017Q4
```
